import React, { useState, useEffect, useRef } from 'react';
import { 
  Trophy, Upload, Users, Settings, Image as ImageIcon, 
  Download, Shield, Crosshair, Zap, FileText, ChevronRight, X, Play, 
  Sliders, Camera, Star, Share2, Globe, MessageCircle,
  Trash2, CheckCircle, AlertTriangle
} from 'lucide-react';

// --- INITIAL CONFIG ---
const INITIAL_TEAMS = [
  { id: 1, name: "Soul Esports", tag: "SOUL", slot: 1 },
  { id: 2, name: "GodLike", tag: "GODL", slot: 2 },
  { id: 3, name: "Team XSpark", tag: "TX", slot: 3 },
  { id: 4, name: "Blind Esports", tag: "BLIND", slot: 4 },
  { id: 5, name: "Orangutan", tag: "OG", slot: 5 },
  { id: 6, name: "Global Esports", tag: "GE", slot: 6 },
  { id: 7, name: "Entity", tag: "ENT", slot: 7 },
  { id: 8, name: "Numen", tag: "NUM", slot: 8 },
];

// --- HELPER: MOCK DATA ---
const generateMockMatchData = (teams, pointSystem) => {
  const currentTeams = teams.length > 0 ? teams : INITIAL_TEAMS;
  const shuffled = [...currentTeams].sort(() => 0.5 - Math.random());
  const count = Math.min(20, shuffled.length);

  return shuffled.slice(0, count).map((team, index) => {
    const kills = Math.floor(Math.random() * 15); 
    const placement = index + 1;
    const placePts = pointSystem.placements[placement] || 0;
    const killPts = kills * pointSystem.killPoint;

    return {
      id: Date.now() + index,
      teamId: team.id,
      teamName: team.name,
      registeredTag: team.tag,
      placement: placement,
      kills: kills,
      placePts: placePts,
      killPts: killPts,
      totalPts: placePts + killPts,
      status: 'verified'
    };
  });
};

// --- COMPONENT: EDITABLE TEXT (Crash Proof) ---
const CardText = ({ value, onChange, className = "", placeholder = "Type here..." }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [localValue, setLocalValue] = useState(value || ""); 

  useEffect(() => { setLocalValue(value || ""); }, [value]);

  const handleBlur = () => {
    setIsEditing(false);
    onChange && onChange(localValue);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') handleBlur();
  };

  if (isEditing) {
    return (
      <input
        autoFocus
        value={localValue}
        onChange={(e) => setLocalValue(e.target.value)}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        className={`bg-black/50 text-white outline-none border-b border-emerald-500 w-full min-w-[20px] ${className}`}
        placeholder={placeholder}
      />
    );
  }

  return (
    <div 
      onClick={() => setIsEditing(true)} 
      className={`cursor-text hover:bg-white/10 rounded px-1 transition-colors border border-transparent hover:border-white/20 whitespace-nowrap overflow-hidden text-ellipsis ${className}`}
      title="Click to edit"
    >
      {value || placeholder}
    </div>
  );
};

// --- MAIN APP ---
export default function ScrimMasterPro() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [teams, setTeams] = useState(INITIAL_TEAMS);
  const [importText, setImportText] = useState('');
  const fileInputRef = useRef(null);
  const [installPrompt, setInstallPrompt] = useState(null);

  // Settings
  const [pointSystem, setPointSystem] = useState({
    killPoint: 1,
    placements: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 4, 7: 2, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1, 13: 0, 14: 0, 15: 0, 16: 0 }
  });

  const [isProcessing, setIsProcessing] = useState(false);
  const [results, setResults] = useState([]);

  // Studio State
  const [cardMode, setCardMode] = useState('standings');
  const [selectedTheme, setSelectedTheme] = useState('cyber');
  const [customBg, setCustomBg] = useState(null);
  const [customLogo, setCustomLogo] = useState(null);
  const [accentColor, setAccentColor] = useState('#00ff9d');
  
  const [organizerName, setOrganizerName] = useState('YOUR ORG NAME');
  const [cardTitle, setCardTitle] = useState('GRAND FINALS');
  const [cardSubtitle, setCardSubtitle] = useState('MATCH 1 RESULTS');
  const [footerText, setFooterText] = useState('Generated by ScrimMaster Pro');
  
  const [tableOpacity, setTableOpacity] = useState(90);
  const [textColor, setTextColor] = useState('light');
  const [tableYOffset, setTableYOffset] = useState(0);
  const [useTwoColumns, setUseTwoColumns] = useState(false);
  
  const [bgBrightness, setBgBrightness] = useState(100);
  const [bgContrast, setBgContrast] = useState(100);
  const [bgSaturation, setBgSaturation] = useState(100);

  const [prizePool, setPrizePool] = useState([
    { rank: "1st Place", amount: "5,000" },
    { rank: "2nd Place", amount: "2,500" },
    { rank: "3rd Place", amount: "1,000" },
    { rank: "MVP", amount: "500" }
  ]);
  
  const [fraggers, setFraggers] = useState([
    { name: "StarPlayer", team: "Soul", kills: 18, img: null },
    { name: "Jonathan", team: "GodL", kills: 15, img: null },
    { name: "ClutchGod", team: "Numen", kills: 14, img: null },
    { name: "Goblin", team: "Soul", kills: 12, img: null },
    { name: "Ninja", team: "OG", kills: 10, img: null }
  ]);
  
  const [winnerDetails, setWinnerDetails] = useState({
      teamName: "TEAM SOUL",
      totalPoints: 75,
      wwcd: 2,
      kills: 45,
      mvp: "Goblin",
      logo: null
  });

  useEffect(() => {
    // Load html2canvas dynamically to prevent crash if offline
    if (!document.getElementById('html2canvas-script')) {
        const script = document.createElement('script');
        script.id = 'html2canvas-script';
        script.src = "https://html2canvas.hertzen.com/dist/html2canvas.min.js";
        script.async = true;
        document.body.appendChild(script);
    }

    const handleBeforeInstall = (e) => { e.preventDefault(); setInstallPrompt(e); };
    window.addEventListener('beforeinstallprompt', handleBeforeInstall);
    return () => window.removeEventListener('beforeinstallprompt', handleBeforeInstall);
  }, []);

  // --- ACTIONS ---

  const handleInstallApp = () => {
    if (!installPrompt) { alert("To install: Tap browser menu (3 dots) -> 'Add to Home Screen'"); return; }
    installPrompt.prompt();
    installPrompt.userChoice.then((choice) => { if (choice.outcome === 'accepted') setInstallPrompt(null); });
  };

  const handleBulkImport = () => {
    if (!importText.trim()) return;
    const lines = importText.split('\n');
    const newTeams = lines.map((line, idx) => {
      const parts = line.split(',').map(s => s.trim());
      let name, tag, slot;
      if (parts.length === 1) { name = parts[0]; tag = name.substring(0,4).toUpperCase(); slot = teams.length + idx + 1; }
      else if (parts.length === 2) { name = parts[0]; tag = parts[1].toUpperCase(); slot = teams.length + idx + 1; }
      else { slot = parseInt(parts[0]) || teams.length + idx + 1; name = parts[1]; tag = parts[2].toUpperCase(); }
      return { id: Date.now() + idx, name, tag, slot };
    }).filter(t => t.name);
    setTeams([...teams, ...newTeams]);
    setImportText('');
  };

  const handleFileSelect = (e) => {
    const files = Array.from(e.target.files);
    if (files.length > 0) {
      setUploadedFiles(files);
      setIsProcessing(true);
      setTimeout(() => {
        const rawData = generateMockMatchData(teams, pointSystem);
        setResults(rawData);
        setIsProcessing(false);
        setActiveTab('validation');
      }, 2000);
    }
  };

  const downloadCard = () => {
    if (!window.html2canvas) { alert('Download module loading... Try again in 5 seconds.'); return; }
    const element = document.getElementById('card-capture');
    window.html2canvas(element, { scale: 2, useCORS: true, backgroundColor: null }).then(canvas => {
      const link = document.createElement('a');
      link.download = `${cardTitle}-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    });
  };

  const updateFragger = (idx, field, val) => {
    const newFraggers = [...fraggers]; newFraggers[idx][field] = val; setFraggers(newFraggers);
  };
  
  const handlePlayerPhotoUpload = (idx, e) => {
    const file = e.target.files[0];
    if (file) {
      const newFraggers = [...fraggers]; newFraggers[idx].img = URL.createObjectURL(file); setFraggers(newFraggers);
    }
  };

  const updateResultRow = (id, field, value) => {
    setResults(prev => prev.map(row => {
      if (row.id !== id) return row;
      const updatedRow = { ...row, [field]: value };
      if (field === 'kills' || field === 'placement') {
        const k = field === 'kills' ? parseInt(value) || 0 : row.kills;
        const p = field === 'placement' ? parseInt(value) || 0 : row.placement;
        updatedRow.killPts = k * pointSystem.killPoint;
        updatedRow.placePts = pointSystem.placements[p] || 0;
        updatedRow.totalPts = updatedRow.killPts + updatedRow.placePts;
      }
      return updatedRow;
    }));
  };

  // --- RENDERERS ---

  const renderSidebar = () => (
    <div className="hidden md:flex flex-col w-64 bg-zinc-900 border-r border-zinc-800 h-screen fixed z-20 p-4">
      <div className="flex items-center gap-2 mb-8 text-emerald-400 font-bold text-2xl tracking-tighter">
        <Crosshair className="w-8 h-8" /> <span className="text-white">SCRIM</span>MASTER
      </div>
      <nav className="flex flex-col gap-2">
        <button onClick={handleInstallApp} className="flex items-center gap-3 p-3 w-full rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold shadow-lg shadow-emerald-900/20 mb-4">
          <Download className="w-5 h-5" /> Install App
        </button>
        {[
          {id: 'dashboard', icon: <Zap />, label: 'Start'},
          {id: 'teams', icon: <Users />, label: '1. Add Teams'},
          {id: 'upload', icon: <Upload />, label: '2. Upload SS'},
          {id: 'validation', icon: <Shield />, label: '3. Edit Data'},
          {id: 'studio', icon: <ImageIcon />, label: '4. Make Card'},
          {id: 'points', icon: <Settings />, label: 'Settings'},
        ].map(item => (
          <button key={item.id} onClick={() => setActiveTab(item.id)} className={`flex items-center gap-3 p-3 w-full rounded-lg text-left font-medium transition-all ${activeTab === item.id ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'text-zinc-400 hover:bg-zinc-800'}`}>
            {item.icon} {item.label}
          </button>
        ))}
      </nav>
    </div>
  );

  const renderStudio = () => (
    <div className="flex h-full flex-col md:flex-row">
      <div className="w-full md:w-80 bg-zinc-900 border-r border-zinc-800 p-6 overflow-y-auto custom-scrollbar">
        <h2 className="text-xl font-bold text-white mb-6">Card Customization</h2>
        
        <div className="mb-6">
            <label className="text-xs font-bold text-zinc-500 uppercase mb-2 block">Card Type</label>
            <div className="grid grid-cols-2 gap-2">
                {['standings', 'fraggers', 'winner', 'announcement'].map(m => (
                    <button key={m} onClick={() => setCardMode(m)} className={`p-2 text-xs font-bold uppercase rounded border ${cardMode === m ? 'bg-emerald-500 text-black border-emerald-500' : 'bg-black text-zinc-400 border-zinc-700'}`}>{m}</button>
                ))}
            </div>
        </div>

        <div className="space-y-6">
           <div>
            <label className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2 block">Theme</label>
            <div className="grid grid-cols-4 gap-2">
              {['cyber', 'clean', 'aggro', 'gold'].map(t => (
                <button key={t} onClick={() => setSelectedTheme(t)} className={`h-8 rounded border ${selectedTheme === t ? 'border-emerald-500 bg-emerald-500/50' : 'border-zinc-700 bg-zinc-800'}`} title={t}></button>
              ))}
            </div>
          </div>

          <div className="space-y-2">
             <label className="text-xs font-bold text-zinc-500 uppercase tracking-wider block">Assets</label>
             <label className="flex items-center gap-2 p-2 bg-black border border-zinc-700 rounded cursor-pointer hover:border-emerald-500">
                <ImageIcon className="w-4 h-4 text-zinc-400" /> <span className="text-xs text-zinc-300">Background Image</span>
                <input type="file" className="hidden" onChange={(e) => e.target.files[0] && setCustomBg(URL.createObjectURL(e.target.files[0]))} />
             </label>
             <label className="flex items-center gap-2 p-2 bg-black border border-zinc-700 rounded cursor-pointer hover:border-emerald-500">
                <Camera className="w-4 h-4 text-zinc-400" /> <span className="text-xs text-zinc-300">Organization Logo</span>
                <input type="file" className="hidden" onChange={(e) => e.target.files[0] && setCustomLogo(URL.createObjectURL(e.target.files[0]))} />
             </label>
          </div>

          <div className="space-y-2 bg-black/20 p-3 rounded border border-zinc-800">
            <label className="text-xs font-bold text-zinc-500 uppercase flex items-center gap-2"><Sliders className="w-3 h-3"/> Color Grading</label>
            <div className="space-y-2 pt-2">
              <div className="flex justify-between text-[10px] text-zinc-400"><span>Brightness</span><span>{bgBrightness}%</span></div>
              <input type="range" min="0" max="200" value={bgBrightness} onChange={e => setBgBrightness(e.target.value)} className="w-full h-1 bg-zinc-700 rounded appearance-none cursor-pointer" />
              <div className="flex justify-between text-[10px] text-zinc-400"><span>Contrast</span><span>{bgContrast}%</span></div>
              <input type="range" min="0" max="200" value={bgContrast} onChange={e => setBgContrast(e.target.value)} className="w-full h-1 bg-zinc-700 rounded appearance-none cursor-pointer" />
              <div className="flex justify-between text-[10px] text-zinc-400"><span>Saturation</span><span>{bgSaturation}%</span></div>
              <input type="range" min="0" max="200" value={bgSaturation} onChange={e => setBgSaturation(e.target.value)} className="w-full h-1 bg-zinc-700 rounded appearance-none cursor-pointer" />
            </div>
          </div>

          <div className="space-y-2 bg-black/20 p-3 rounded border border-zinc-800">
             <label className="text-xs font-bold text-zinc-500 uppercase">Appearance</label>
             <div className="flex items-center justify-between"><span className="text-xs text-zinc-400">Accent</span><input type="color" value={accentColor} onChange={e => setAccentColor(e.target.value)} className="bg-transparent w-6 h-6 cursor-pointer" /></div>
             <div className="flex items-center justify-between"><span className="text-xs text-zinc-400">Text Mode</span><div className="flex bg-zinc-800 rounded p-0.5"><button onClick={() => setTextColor('light')} className={`px-2 py-0.5 text-[10px] rounded ${textColor === 'light' ? 'bg-zinc-600 text-white' : 'text-zinc-500'}`}>Light</button><button onClick={() => setTextColor('dark')} className={`px-2 py-0.5 text-[10px] rounded ${textColor === 'dark' ? 'bg-zinc-600 text-white' : 'text-zinc-500'}`}>Dark</button></div></div>
             {cardMode === 'standings' && (
                <div className="flex items-center justify-between"><span className="text-xs text-zinc-400">2 Columns</span><input type="checkbox" checked={useTwoColumns} onChange={e => setUseTwoColumns(e.target.checked)} className="accent-emerald-500" /></div>
             )}
             <div className="pt-2"><span className="text-xs text-zinc-400 block mb-1">Table Opacity ({tableOpacity}%)</span><input type="range" min="0" max="100" value={tableOpacity} onChange={e => setTableOpacity(e.target.value)} className="w-full h-1 bg-zinc-700 rounded appearance-none cursor-pointer" /></div>
             <div className="pt-2"><span className="text-xs text-zinc-400 block mb-1">Position Y ({tableYOffset}px)</span><input type="range" min="0" max="200" value={tableYOffset} onChange={e => setTableYOffset(e.target.value)} className="w-full h-1 bg-zinc-700 rounded appearance-none cursor-pointer" /></div>
          </div>
          
          <button onClick={downloadCard} className="w-full bg-emerald-500 hover:bg-emerald-400 text-black font-bold py-3 rounded flex items-center justify-center gap-2"><Download className="w-4 h-4" /> Download HD Image</button>
        </div>
      </div>

      <div className="flex-1 bg-zinc-950 flex items-center justify-center p-8 overflow-auto">
        <div id="card-capture" className="w-[1080px] min-h-[1080px] shadow-2xl relative overflow-hidden flex flex-col" style={{ backgroundColor: selectedTheme === 'clean' || textColor === 'dark' ? '#f0f0f0' : '#09090b', color: textColor === 'dark' ? '#000' : '#fff' }}>
            <div className="absolute inset-0 w-full h-full" style={{ filter: `brightness(${bgBrightness}%) contrast(${bgContrast}%) saturate(${bgSaturation}%)` }}>
                {customBg ? ( <img src={customBg} className="absolute inset-0 w-full h-full object-cover" alt="" /> ) : (
                <>
                {selectedTheme === 'cyber' && <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-zinc-800 via-black to-black"></div>}
                {selectedTheme === 'aggro' && <div className="absolute inset-0 bg-red-950 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')]"></div>}
                {selectedTheme === 'gold' && <div className="absolute inset-0 bg-gradient-to-br from-yellow-950 via-black to-black"></div>}
                </>
                )}
            </div>
            <div className="absolute inset-0 pointer-events-none opacity-20" style={{ background: `radial-gradient(circle at 50% 0%, ${accentColor}, transparent 70%)` }}></div>

            <div className="relative z-10 p-12 flex justify-between items-start border-b border-white/10" style={{ borderColor: accentColor }}>
              <div className="flex flex-col gap-1 w-full">
                 <div className="flex items-center gap-3">
                    {customLogo && <img src={customLogo} className="w-20 h-20 object-contain drop-shadow-lg" alt="Org" />}
                    <div className="w-full">
                        <div className="text-sm font-bold tracking-[0.4em] uppercase opacity-70 mb-1"><CardText value={organizerName} onChange={setOrganizerName} /></div>
                        <h1 className="text-6xl font-black uppercase italic tracking-tighter leading-none drop-shadow-lg"><CardText value={cardTitle} onChange={setCardTitle} /></h1>
                        <div className="text-2xl font-bold uppercase tracking-widest opacity-90" style={{ color: accentColor }}><CardText value={cardSubtitle} onChange={setCardSubtitle} /></div>
                    </div>
                 </div>
              </div>
              <div className="text-right hidden md:block w-64">
                 <div className="w-24 h-1 mb-2 ml-auto" style={{ backgroundColor: accentColor }}></div>
                 <div className="text-xs font-bold opacity-50 uppercase tracking-widest">Powered By</div>
                 <div className="text-xl font-bold">SCRIMMASTER</div>
              </div>
            </div>

            <div className="relative z-10 p-8 flex-1 transition-all duration-300" style={{ paddingTop: `${parseInt(tableYOffset) + 30}px` }}>
               {cardMode === 'standings' && (
                 <div className={useTwoColumns ? "grid grid-cols-2 gap-x-8 gap-y-2" : "flex flex-col gap-2"}>
                    {!useTwoColumns && (
                        <div className="grid grid-cols-12 gap-4 text-sm font-bold opacity-70 uppercase mb-2 px-6 py-2 rounded" style={{ backgroundColor: textColor === 'dark' ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)' }}>
                            <div className="col-span-1">#</div><div className="col-span-5">Team Name</div><div className="col-span-2 text-center">WWCD</div><div className="col-span-1 text-center">PP</div><div className="col-span-1 text-center">KP</div><div className="col-span-2 text-center">Total</div>
                        </div>
                    )}
                    {results.slice(0, useTwoColumns ? 32 : 16).map((r, i) => (
                        <div key={i} className={`grid grid-cols-12 gap-4 items-center px-6 py-3 rounded-lg relative overflow-hidden transition-all ${useTwoColumns ? 'text-xs' : ''}`} style={{ backgroundColor: i === 0 ? accentColor : (textColor === 'dark' ? `rgba(255,255,255,${tableOpacity/100})` : `rgba(20,20,20,${tableOpacity/100})`), color: i === 0 ? '#000' : 'inherit', boxShadow: '0 4px 6px rgba(0,0,0,0.1)' }}> 
                            <div className="col-span-1 font-mono font-black text-xl opacity-80">{i + 1 < 10 ? `0${i+1}` : i+1}</div>
                            <div className="col-span-5 font-bold uppercase tracking-tight text-lg truncate flex items-center gap-2">
                                <CardText value={r.teamName} onChange={(val) => updateResultRow(r.id, 'teamName', val)} /> {i === 0 && <Trophy className="w-5 h-5" />}
                            </div>
                            <div className="col-span-2 text-center font-mono font-bold opacity-80">{r.placement === 1 ? '1' : '-'}</div>
                            <div className="col-span-1 text-center font-mono opacity-80">{r.placePts}</div>
                            <div className="col-span-1 text-center font-mono opacity-80">{r.killPts}</div>
                            <div className="col-span-2 text-center text-2xl font-black">{r.totalPts}</div>
                        </div>
                    ))}
                 </div>
               )}
               {cardMode === 'announcement' && (
                 <div className="h-full flex flex-col items-center justify-center gap-8">
                    <div className="w-full max-w-3xl bg-black/40 backdrop-blur-md border-t-4 border-b-4 p-12 text-center rounded-xl" style={{ borderColor: accentColor }}>
                        <h2 className="text-5xl font-black uppercase italic tracking-tighter mb-8 text-white drop-shadow-lg"><CardText value="Prize Pool Distribution" /></h2>
                        <div className="grid grid-cols-2 gap-6">
                            {prizePool.map((p, i) => (
                                <div key={i} className="bg-gradient-to-r from-zinc-900 to-black p-6 rounded border border-zinc-800 flex justify-between items-center group hover:border-emerald-500 transition-colors">
                                    <span className="text-xl font-bold text-zinc-400 uppercase"><CardText value={p.rank} onChange={(v) => {const n=[...prizePool]; n[i].rank=v; setPrizePool(n)}} /></span>
                                    <span className="text-4xl font-black text-white group-hover:text-emerald-400" style={{ color: i===0 ? accentColor : 'white' }}><CardText value={p.amount} onChange={(v) => {const n=[...prizePool]; n[i].amount=v; setPrizePool(n)}} /></span>
                                </div>
                            ))}
                        </div>
                    </div>
                 </div>
               )}
               {cardMode === 'winner' && (
                 <div className="h-full flex flex-col items-center justify-center gap-6">
                    <div className="w-full max-w-4xl bg-black/40 backdrop-blur-md border border-zinc-700 p-12 text-center rounded-3xl relative overflow-hidden">
                        <div className="absolute inset-0 bg-gradient-to-t from-black/80 to-transparent"></div>
                        <div className="relative z-10">
                            <div className="w-48 h-48 mx-auto mb-6 bg-black rounded-full border-4 flex items-center justify-center overflow-hidden" style={{ borderColor: accentColor }}>
                                {winnerDetails.logo ? ( <img src={winnerDetails.logo} className="w-full h-full object-cover" /> ) : ( <Star className="w-24 h-24 text-zinc-700" /> )}
                                <input type="file" className="absolute inset-0 opacity-0 cursor-pointer" onChange={(e) => e.target.files[0] && setWinnerDetails({...winnerDetails, logo: URL.createObjectURL(e.target.files[0])})} />
                            </div>
                            <h2 className="text-3xl font-bold text-emerald-400 tracking-[0.5em] mb-2">WINNER WINNER CHICKEN DINNER</h2>
                            <h1 className="text-8xl font-black uppercase italic tracking-tighter mb-8 text-white drop-shadow-2xl"><CardText value={winnerDetails.teamName} onChange={v => setWinnerDetails({...winnerDetails, teamName: v})} /></h1>
                            <div className="grid grid-cols-3 gap-8 max-w-2xl mx-auto">
                                <div className="p-4 bg-zinc-900/80 rounded-xl border border-zinc-700"><div className="text-sm text-zinc-400 uppercase tracking-widest">Total Points</div><div className="text-5xl font-black text-white"><CardText value={winnerDetails.totalPoints} onChange={v => setWinnerDetails({...winnerDetails, totalPoints: v})} /></div></div>
                                <div className="p-4 bg-zinc-900/80 rounded-xl border border-zinc-700"><div className="text-sm text-zinc-400 uppercase tracking-widest">WWCD</div><div className="text-5xl font-black" style={{ color: accentColor }}><CardText value={winnerDetails.wwcd} onChange={v => setWinnerDetails({...winnerDetails, wwcd: v})} /></div></div>
                                <div className="p-4 bg-zinc-900/80 rounded-xl border border-zinc-700"><div className="text-sm text-zinc-400 uppercase tracking-widest">Team Kills</div><div className="text-5xl font-black text-white"><CardText value={winnerDetails.kills} onChange={v => setWinnerDetails({...winnerDetails, kills: v})} /></div></div>
                            </div>
                        </div>
                    </div>
                 </div>
               )}
               {cardMode === 'fraggers' && (
                 <div className="grid grid-cols-1 gap-4 max-w-4xl mx-auto">
                    {fraggers.map((p, i) => (
                        <div key={i} className="flex items-center justify-between p-6 rounded-xl border-l-8 bg-black/40 backdrop-blur-sm" style={{ borderLeftColor: i===0 ? accentColor : 'transparent', backgroundColor: `rgba(20,20,20,${tableOpacity/100})` }}>
                             <div className="flex items-center gap-6">
                                <span className="text-6xl font-black opacity-20 italic">0{i+1}</span>
                                <div className="relative group cursor-pointer w-20 h-20 rounded-full bg-black border-2 border-zinc-700 overflow-hidden">
                                  {p.img ? ( <img src={p.img} className="w-full h-full object-cover" /> ) : ( <div className="w-full h-full flex items-center justify-center text-zinc-600"><Camera className="w-6 h-6"/></div> )}
                                  <input type="file" className="hidden absolute inset-0 cursor-pointer" onChange={(e) => handlePlayerPhotoUpload(i, e)} />
                                </div>
                                <div>
                                    <div className="text-3xl font-black uppercase"><CardText value={p.name} onChange={(v) => updateFragger(i, 'name', v)} /></div>
                                    <div className="text-lg opacity-60 uppercase tracking-widest"><CardText value={p.team} onChange={(v) => updateFragger(i, 'team', v)} /></div>
                                </div>
                             </div>
                             <div className="text-center">
                                <div className="text-5xl font-black" style={{ color: accentColor }}><CardText value={p.kills} onChange={(v) => updateFragger(i, 'kills', v)} /></div>
                                <div className="text-xs font-bold uppercase tracking-widest opacity-50">Kills</div>
                             </div>
                        </div>
                    ))}
                 </div>
               )}
            </div>

            <div className="relative z-10 p-6 flex justify-between items-center bg-black/80 text-white backdrop-blur-md border-t border-white/10">
                <div className="flex items-center gap-4">
                    <div className="text-xs font-bold tracking-widest uppercase opacity-60">Follow Us</div>
                    <div className="flex gap-2 text-lg">
                        <Share2 className="w-5 h-5"/> <Globe className="w-5 h-5"/> <MessageCircle className="w-5 h-5"/>
                    </div>
                </div>
                <div className="text-xs font-mono opacity-40 uppercase"><CardText value={footerText} onChange={setFooterText} /></div>
            </div>
          </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-emerald-500 selection:text-black">
      <div className="md:hidden p-4 bg-zinc-900 border-b border-zinc-800 flex justify-between items-center">
        <span className="font-bold text-emerald-400">SCRIMMASTER</span>
        <button onClick={() => setActiveTab('dashboard')}><Settings className="w-5 h-5"/></button>
      </div>
      {renderSidebar()}
      <main className="md:ml-64 h-screen overflow-y-auto">
        {activeTab === 'dashboard' && (
             <div className="p-10 flex flex-col items-center justify-center h-full text-center animate-fade-in">
             <div className="w-20 h-20 bg-emerald-500/10 rounded-full flex items-center justify-center mb-6 text-emerald-400"><Trophy className="w-10 h-10" /></div>
             <h1 className="text-5xl font-black text-white mb-4">ESPORTS MANAGER PRO</h1>
             <p className="text-zinc-400 max-w-lg text-lg mb-8">Professional automated scorecard generator.</p>
             <button onClick={() => setActiveTab('teams')} className="group bg-emerald-500 hover:bg-emerald-400 text-black px-8 py-4 rounded-full font-bold text-xl flex items-center gap-3 transition-all transform hover:scale-105">Start New Tournament <ChevronRight className="group-hover:translate-x-1 transition-transform"/></button>
           </div>
        )}
        {activeTab === 'teams' && (
            <div className="p-8 max-w-5xl mx-auto">
            <div className="flex justify-between items-center mb-6"><h1 className="text-3xl font-bold text-white">Step 1: Add Teams</h1><span className="text-zinc-500 text-sm">Supports Auto-Tagging</span></div>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <div className="space-y-4">
                <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800"><textarea value={importText} onChange={(e) => setImportText(e.target.value)} className="w-full h-48 bg-black border border-zinc-700 text-white p-4 rounded-lg font-mono text-sm focus:border-emerald-500 outline-none" placeholder="Paste List Here..."/><button onClick={handleBulkImport} className="w-full mt-4 bg-zinc-800 hover:bg-zinc-700 text-white py-3 rounded-lg font-bold flex items-center justify-center gap-2 border border-zinc-700"><FileText className="w-4 h-4" /> Add to Roster</button></div>
              </div>
              <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800 flex flex-col h-[400px]">
                <div className="flex justify-between items-center mb-4 pb-4 border-b border-zinc-800"><h3 className="font-bold text-white">Registered Teams ({teams.length})</h3><button onClick={() => setTeams([])} className="text-red-400 text-xs hover:underline flex items-center gap-1"><Trash2 className="w-3 h-3"/> Clear</button></div>
                <div className="overflow-y-auto flex-1 space-y-2 pr-2 custom-scrollbar">
                  {teams.map((t, i) => (
                    <div key={i} className="flex items-center gap-3 bg-black/40 p-2 rounded border border-zinc-800/50"><span className="w-6 h-6 bg-zinc-800 rounded flex items-center justify-center text-xs text-zinc-400">{t.slot}</span><div className="flex-1"><div className="text-sm font-bold text-zinc-200">{t.name}</div></div><div className="px-2 py-1 bg-emerald-500/10 text-emerald-400 text-xs font-mono rounded border border-emerald-500/20">{t.tag}</div></div>
                  ))}
                </div>
              </div>
            </div>
            <div className="fixed bottom-0 left-0 md:left-64 right-0 p-4 bg-zinc-900/90 border-t border-zinc-800 flex justify-end backdrop-blur-md"><button onClick={() => setActiveTab('upload')} disabled={teams.length === 0} className="bg-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-emerald-400 text-black px-6 py-3 rounded-lg font-bold flex items-center gap-2">Next: Upload Screenshots <ChevronRight className="w-5 h-5" /></button></div>
          </div>
        )}
        {activeTab === 'upload' && (
            <div className="p-8 h-full flex flex-col justify-center items-center">
            <h1 className="text-3xl font-bold text-white mb-2">Step 2: Upload Screenshots</h1>
            <p className="text-zinc-400 mb-8">Upload your end-game screenshots. We will extract data.</p>
            <input type="file" multiple ref={fileInputRef} onChange={handleFileSelect} className="hidden" accept="image/*"/>
            <div onClick={() => fileInputRef.current.click()} className="w-full max-w-2xl h-64 border-2 border-dashed border-zinc-700 hover:border-emerald-500 hover:bg-zinc-900/50 rounded-2xl flex flex-col items-center justify-center cursor-pointer transition-all group relative overflow-hidden">
              {isProcessing ? ( <div className="absolute inset-0 bg-black/90 flex flex-col items-center justify-center z-10"><div className="w-12 h-12 border-4 border-emerald-500 border-t-transparent rounded-full animate-spin mb-4"></div><p className="text-emerald-400 font-bold tracking-widest animate-pulse">ANALYZING {uploadedFiles.length} SCREENSHOTS...</p><p className="text-zinc-500 text-sm mt-2">Extracting kills & placement...</p></div> ) : ( <><Upload className="w-16 h-16 text-zinc-500 group-hover:text-emerald-400 mb-4 transition-colors" /><h3 className="text-xl font-bold text-white">Click to Upload Images</h3><p className="text-zinc-500 mt-2">Supported: JPG, PNG, WEBP</p></> )}
            </div>
          </div>
        )}
        {activeTab === 'validation' && (
             <div className="p-8 pb-24">
             <div className="flex justify-between items-center mb-6"><div><h1 className="text-3xl font-bold text-white">Step 3: Review & Edit</h1><p className="text-zinc-400 text-sm">Click any value to edit instantly.</p></div><button onClick={() => setResults([...results].sort((a,b) => b.totalPts - a.totalPts))} className="text-zinc-400 hover:text-white flex items-center gap-2 text-sm"><Play className="w-3 h-3" /> Re-Sort Rank</button></div>
             <div className="bg-zinc-900 rounded-xl border border-zinc-800 overflow-hidden shadow-2xl">
               <div className="overflow-x-auto">
                 <table className="w-full text-left border-collapse">
                   <thead className="bg-black text-zinc-400 text-xs uppercase font-bold tracking-wider"><tr><th className="p-4 w-16 text-center">#</th><th className="p-4">Team Name</th><th className="p-4 text-center w-24">Place</th><th className="p-4 text-center w-24">Kills</th><th className="p-4 text-center w-24">Total</th><th className="p-4 text-right w-20"></th></tr></thead>
                   <tbody className="divide-y divide-zinc-800 text-sm">
                     {results.map((row, idx) => (
                       <tr key={row.id} className="hover:bg-white/5 transition-colors group">
                         <td className="p-4 text-center font-mono text-zinc-500">{idx + 1}</td>
                         <td className="p-4"><CardText value={row.teamName} onChange={(val) => updateResultRow(row.id, 'teamName', val)} className="font-bold text-white text-lg" /></td>
                         <td className="p-4 text-center"><CardText value={row.placement} onChange={(val) => updateResultRow(row.id, 'placement', val)} className="font-mono text-zinc-300 text-center" /></td>
                         <td className="p-4 text-center"><CardText value={row.kills} onChange={(val) => updateResultRow(row.id, 'kills', val)} className="font-mono text-white font-bold text-center" /></td>
                         <td className="p-4 text-center"><div className="text-xl font-black text-emerald-400">{row.totalPts}</div></td>
                         <td className="p-4 text-right"><button onClick={() => setResults(results.filter(r => r.id !== row.id))} className="text-zinc-600 hover:text-red-500 opacity-0 group-hover:opacity-100 transition-opacity"><X className="w-5 h-5" /></button></td>
                       </tr>
                     ))}
                   </tbody>
                 </table>
               </div>
             </div>
             <div className="fixed bottom-0 left-0 md:left-64 right-0 p-4 bg-zinc-900/90 border-t border-zinc-800 flex justify-end backdrop-blur-md"><button onClick={() => setActiveTab('studio')} className="bg-emerald-500 hover:bg-emerald-400 text-black px-6 py-3 rounded-lg font-bold flex items-center gap-2">Next: Generate Card <ChevronRight className="w-5 h-5" /></button></div>
           </div>
        )}
        {activeTab === 'studio' && renderStudio()}
        {activeTab === 'points' && (
             <div className="p-8 pb-32">
             <h1 className="text-3xl font-bold mb-4">Settings</h1>
             <div className="grid grid-cols-1 gap-6">
               <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800"><h3 className="font-bold mb-4 flex items-center gap-2"><Crosshair className="w-5 h-5 text-red-400"/> Kill Points</h3><div className="flex items-center gap-4"><label className="text-zinc-400 text-sm">Points per Kill:</label><input type="number" value={pointSystem.killPoint} onChange={(e) => setPointSystem({...pointSystem, killPoint: e.target.value})} className="bg-black border border-zinc-700 p-2 rounded w-24 text-white text-center font-bold text-lg" /></div></div>
               <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800"><h3 className="font-bold mb-4 flex items-center gap-2"><Trophy className="w-5 h-5 text-yellow-400"/> Placement Points</h3><div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-3">{Object.entries(pointSystem.placements).map(([rank, pts]) => (<div key={rank} className="bg-black p-2 rounded border border-zinc-800 flex flex-col items-center"><span className="text-[10px] text-zinc-500 uppercase font-bold">Rank #{rank}</span><input type="number" value={pts} onChange={(e) => setPointSystem(prev => ({...prev, placements: { ...prev.placements, [rank]: parseInt(e.target.value) || 0 }}))} className="bg-transparent text-white text-center font-bold w-full outline-none"/></div>))}</div></div>
             </div>
           </div>
        )}
      </main>
    </div>
  );
}