import React, { useState, useEffect, useRef } from 'react';
import { 
  Trophy, Upload, Users, Settings, Image as ImageIcon, 
  Download, Shield, Crosshair, Zap, FileText, ChevronRight, X, Play, 
  Sliders, Camera, Star, Share2, Globe, MessageCircle,
  Plus, Trash2, Save, Move, AlertOctagon, Maximize
} from 'lucide-react';

// --- INITIAL CONFIG ---
const INITIAL_TEAMS = [
  { id: 1, name: "Soul Esports", tag: "SOUL", slot: 1 },
  { id: 2, name: "GodLike", tag: "GODL", slot: 2 },
  { id: 3, name: "Team XSpark", tag: "TX", slot: 3 },
  { id: 4, name: "Blind Esports", tag: "BLIND", slot: 4 },
  { id: 5, name: "Orangutan", tag: "OG", slot: 5 },
  { id: 6, name: "Global Esports", tag: "GE", slot: 6 },
  { id: 7, name: "Entity", tag: "ENT", slot: 7 },
  { id: 8, name: "Numen", tag: "NUM", slot: 8 },
];

// --- COMPONENT: EDITABLE TEXT ---
const CardText = ({ value, onChange, className = "", placeholder = "Type..." }) => {
  const [isEditing, setIsEditing] = useState(false);
  const [localValue, setLocalValue] = useState(value || ""); 

  useEffect(() => { setLocalValue(value || ""); }, [value]);

  const handleBlur = () => {
    setIsEditing(false);
    onChange && onChange(localValue);
  };

  const handleKeyDown = (e) => {
    if (e.key === 'Enter') handleBlur();
  };

  if (isEditing) {
    return (
      <input
        autoFocus
        value={localValue}
        onChange={(e) => setLocalValue(e.target.value)}
        onBlur={handleBlur}
        onKeyDown={handleKeyDown}
        className={`bg-transparent text-inherit outline-none border-b border-emerald-500 w-full min-w-[20px] ${className}`}
        placeholder={placeholder}
      />
    );
  }

  return (
    <div 
      onClick={() => setIsEditing(true)} 
      className={`cursor-text hover:bg-white/10 rounded px-1 transition-colors border border-transparent hover:border-white/20 whitespace-nowrap overflow-hidden text-ellipsis ${className}`}
      title="Click to edit"
    >
      {value || placeholder}
    </div>
  );
};

// --- MAIN APP ---
export default function ScrimMasterPro() {
  const [activeTab, setActiveTab] = useState('dashboard');
  const [teams, setTeams] = useState(INITIAL_TEAMS);
  const [importText, setImportText] = useState('');
  const [installPrompt, setInstallPrompt] = useState(null);

  // Settings
  const [pointSystem, setPointSystem] = useState({
    killPoint: 1,
    placements: { 1: 15, 2: 12, 3: 10, 4: 8, 5: 6, 6: 4, 7: 2, 8: 1, 9: 1, 10: 1, 11: 1, 12: 1, 13: 0, 14: 0, 15: 0, 16: 0 }
  });

  // Data Entry State
  const [matchEntries, setMatchEntries] = useState([]);
  const [results, setResults] = useState([]);
  const [duplicateWarning, setDuplicateWarning] = useState(null);

  // Studio State
  const [cardMode, setCardMode] = useState('standings');
  const [selectedTheme, setSelectedTheme] = useState('cyber');
  const [customBg, setCustomBg] = useState(null);
  const [customLogo, setCustomLogo] = useState(null);
  const [accentColor, setAccentColor] = useState('#00ff9d');
  
  const [organizerName, setOrganizerName] = useState('YOUR ORG NAME');
  const [cardTitle, setCardTitle] = useState('GRAND FINALS');
  const [cardSubtitle, setCardSubtitle] = useState('MATCH 1 RESULTS');
  const [footerText, setFooterText] = useState('Generated by ScrimMaster Pro');
  
  // Advanced Customization (Overlay Controls)
  const [tableOpacity, setTableOpacity] = useState(90);
  const [textColor, setTextColor] = useState('light');
  const [tableYOffset, setTableYOffset] = useState(0);
  const [tableXOffset, setTableXOffset] = useState(0);
  const [rowSpacing, setRowSpacing] = useState(8); 
  const [fontSize, setFontSize] = useState(16);
  const [useTwoColumns, setUseTwoColumns] = useState(false);
  const [cardScale, setCardScale] = useState(100); // NEW: Zoom/Scale
  const [tableWidth, setTableWidth] = useState(100); // NEW: Width %
  
  const [bgBrightness, setBgBrightness] = useState(100);
  const [bgContrast, setBgContrast] = useState(100);
  const [bgSaturation, setBgSaturation] = useState(100);

  // Initialize Match Entries based on Teams
  useEffect(() => {
    const newEntries = teams.map(t => {
        const existing = matchEntries.find(e => e.teamId === t.id);
        return existing ? existing : {
            teamId: t.id,
            teamName: t.name,
            tag: t.tag,
            slot: t.slot,
            place: '',
            kills: ''
        };
    }).sort((a, b) => a.slot - b.slot);
    setMatchEntries(newEntries);
  }, [teams]);

  // DUPLICATE CHECKER
  useEffect(() => {
    const places = matchEntries.map(e => e.place).filter(p => p !== '' && p !== '0');
    const duplicates = places.filter((item, index) => places.indexOf(item) !== index);
    if (duplicates.length > 0) {
      setDuplicateWarning(`Warning: Rank ${[...new Set(duplicates)].join(', ')} is assigned to multiple teams!`);
    } else {
      setDuplicateWarning(null);
    }
  }, [matchEntries]);

  // Load HTML2Canvas
  useEffect(() => {
    if (!document.getElementById('html2canvas-script')) {
        const script = document.createElement('script');
        script.id = 'html2canvas-script';
        script.src = "https://html2canvas.hertzen.com/dist/html2canvas.min.js";
        script.async = true;
        document.body.appendChild(script);
    }
    const handleBeforeInstall = (e) => { e.preventDefault(); setInstallPrompt(e); };
    window.addEventListener('beforeinstallprompt', handleBeforeInstall);
    return () => window.removeEventListener('beforeinstallprompt', handleBeforeInstall);
  }, []);

  // --- LOGIC ---
  const calculateResults = () => {
    if (duplicateWarning) {
        if(!confirm("Warning: Duplicate Ranks detected. Continue anyway?")) return;
    }

    const calculated = matchEntries.map(entry => {
        const p = parseInt(entry.place) || 0;
        const k = parseInt(entry.kills) || 0;
        const pPts = pointSystem.placements[p] || 0;
        const kPts = k * pointSystem.killPoint;
        return {
            ...entry,
            placement: p,
            kills: k,
            placePts: pPts,
            killPts: kPts,
            totalPts: pPts + kPts
        };
    }).filter(e => e.totalPts > 0 || e.placement > 0); 

    calculated.sort((a, b) => b.totalPts - a.totalPts || b.killPts - a.killPts);
    setResults(calculated);
    setActiveTab('studio');
  };

  // --- ACTIONS ---
  const handleInstallApp = () => {
    if (!installPrompt) { alert("To install: Tap browser menu (3 dots) -> 'Add to Home Screen'"); return; }
    installPrompt.prompt();
    installPrompt.userChoice.then((choice) => { if (choice.outcome === 'accepted') setInstallPrompt(null); });
  };

  const handleBulkImport = () => {
    if (!importText.trim()) return;
    const lines = importText.split('\n');
    const newTeams = lines.map((line, idx) => {
      const parts = line.split(',').map(s => s.trim());
      let name, tag, slot;
      if (parts.length === 1) { name = parts[0]; tag = name.substring(0,4).toUpperCase(); slot = teams.length + idx + 1; }
      else if (parts.length === 2) { name = parts[0]; tag = parts[1].toUpperCase(); slot = teams.length + idx + 1; }
      else { slot = parseInt(parts[0]) || teams.length + idx + 1; name = parts[1]; tag = parts[2].toUpperCase(); }
      return { id: Date.now() + idx, name, tag, slot };
    }).filter(t => t.name);
    setTeams([...teams, ...newTeams]);
    setImportText('');
  };

  const downloadCard = () => {
    if (!window.html2canvas) { alert('Download module loading... Try again in 5 seconds.'); return; }
    const element = document.getElementById('card-capture');
    window.html2canvas(element, { scale: 2, useCORS: true, backgroundColor: null }).then(canvas => {
      const link = document.createElement('a');
      link.download = `${cardTitle}-${Date.now()}.png`;
      link.href = canvas.toDataURL('image/png');
      link.click();
    });
  };

  const handleEntryChange = (id, field, value) => {
      setMatchEntries(prev => prev.map(e => e.teamId === id ? { ...e, [field]: value } : e));
  };

  const updateResultRow = (id, field, value) => {
    setResults(prev => prev.map(row => {
      if (row.id !== id) return row;
      const updatedRow = { ...row, [field]: value };
      if (field === 'kills' || field === 'placement') {
        const k = field === 'kills' ? parseInt(value) || 0 : row.kills;
        const p = field === 'placement' ? parseInt(value) || 0 : row.placement;
        updatedRow.killPts = k * pointSystem.killPoint;
        updatedRow.placePts = pointSystem.placements[p] || 0;
        updatedRow.totalPts = updatedRow.killPts + updatedRow.placePts;
      }
      return updatedRow;
    }));
  };

  // --- RENDERERS ---

  const renderSidebar = () => (
    <div className="hidden md:flex flex-col w-64 bg-zinc-900 border-r border-zinc-800 h-screen fixed z-20 p-4">
      <div className="flex items-center gap-2 mb-8 text-emerald-400 font-bold text-2xl tracking-tighter">
        <Crosshair className="w-8 h-8" /> <span className="text-white">SCRIM</span>MASTER
      </div>
      <nav className="flex flex-col gap-2">
        <button onClick={handleInstallApp} className="flex items-center gap-3 p-3 w-full rounded-lg bg-emerald-600 hover:bg-emerald-500 text-white font-bold shadow-lg shadow-emerald-900/20 mb-4">
          <Download className="w-5 h-5" /> Install App
        </button>
        {[
          {id: 'dashboard', icon: <Zap />, label: 'Start'},
          {id: 'teams', icon: <Users />, label: '1. Add Teams'},
          {id: 'entry', icon: <FileText />, label: '2. Enter Data'},
          {id: 'studio', icon: <ImageIcon />, label: '3. Card Studio'},
          {id: 'points', icon: <Settings />, label: 'Settings'},
        ].map(item => (
          <button key={item.id} onClick={() => setActiveTab(item.id)} className={`flex items-center gap-3 p-3 w-full rounded-lg text-left font-medium transition-all ${activeTab === item.id ? 'bg-emerald-500/10 text-emerald-400 border border-emerald-500/20' : 'text-zinc-400 hover:bg-zinc-800'}`}>
            {item.icon} {item.label}
          </button>
        ))}
      </nav>
    </div>
  );

  const renderDataEntry = () => (
      <div className="p-8 pb-32 max-w-4xl mx-auto">
          <div className="flex justify-between items-center mb-6">
              <h1 className="text-3xl font-bold text-white">Step 2: Enter Match Results</h1>
              <button onClick={calculateResults} className="bg-emerald-500 hover:bg-emerald-400 text-black px-6 py-2 rounded-lg font-bold flex items-center gap-2">
                  <Play className="w-4 h-4" /> Generate Result
              </button>
          </div>
          
          {duplicateWarning && (
            <div className="mb-6 bg-red-500/20 border border-red-500 text-red-200 p-4 rounded-lg flex items-center gap-3 animate-pulse">
                <AlertOctagon className="w-6 h-6" />
                <span className="font-bold">{duplicateWarning}</span>
            </div>
          )}
          
          <div className="bg-zinc-900 border border-zinc-800 rounded-xl overflow-hidden">
              <div className="grid grid-cols-12 bg-black p-3 text-xs font-bold text-zinc-500 uppercase">
                  <div className="col-span-1 text-center">Slot</div>
                  <div className="col-span-5">Team Name</div>
                  <div className="col-span-3 text-center">Rank #</div>
                  <div className="col-span-3 text-center">Kills</div>
              </div>
              <div className="divide-y divide-zinc-800 max-h-[60vh] overflow-y-auto">
                  {matchEntries.map((entry) => (
                      <div key={entry.teamId} className={`grid grid-cols-12 p-2 items-center hover:bg-white/5 transition-colors ${matchEntries.filter(e => e.place === entry.place && e.place !== '').length > 1 ? 'bg-red-900/20' : ''}`}>
                          <div className="col-span-1 text-center font-mono text-zinc-400 bg-black/50 rounded py-1 mx-2">{entry.slot}</div>
                          <div className="col-span-5 font-bold text-white truncate px-2">{entry.teamName}</div>
                          <div className="col-span-3 px-2">
                              <input 
                                type="number" 
                                placeholder="-" 
                                value={entry.place}
                                onChange={(e) => handleEntryChange(entry.teamId, 'place', e.target.value)}
                                className={`w-full bg-black border text-white text-center rounded py-1 focus:outline-none ${matchEntries.filter(e => e.place === entry.place && e.place !== '').length > 1 ? 'border-red-500' : 'border-zinc-700 focus:border-emerald-500'}`}
                              />
                          </div>
                          <div className="col-span-3 px-2">
                              <input 
                                type="number" 
                                placeholder="0" 
                                value={entry.kills}
                                onChange={(e) => handleEntryChange(entry.teamId, 'kills', e.target.value)}
                                className="w-full bg-black border border-zinc-700 text-white text-center rounded py-1 focus:border-emerald-500 focus:outline-none font-bold"
                              />
                          </div>
                      </div>
                  ))}
              </div>
          </div>
          <div className="mt-4 text-center text-zinc-500 text-sm">
              Note: Duplicate ranks will be highlighted in red.
          </div>
      </div>
  );

  const renderStudio = () => (
    <div className="flex h-full flex-col md:flex-row">
      <div className="w-full md:w-80 bg-zinc-900 border-r border-zinc-800 p-6 overflow-y-auto custom-scrollbar">
        <h2 className="text-xl font-bold text-white mb-6">Card Customization</h2>
        
        <div className="mb-6">
            <label className="text-xs font-bold text-zinc-500 uppercase mb-2 block">Card Type</label>
            <div className="grid grid-cols-2 gap-2">
                {['standings', 'winner'].map(m => (
                    <button key={m} onClick={() => setCardMode(m)} className={`p-2 text-xs font-bold uppercase rounded border ${cardMode === m ? 'bg-emerald-500 text-black border-emerald-500' : 'bg-black text-zinc-400 border-zinc-700'}`}>{m}</button>
                ))}
            </div>
        </div>

        <div className="space-y-6">
           <div>
            <label className="text-xs font-bold text-zinc-500 uppercase tracking-wider mb-2 block">Theme</label>
            <div className="grid grid-cols-4 gap-2">
              {['cyber', 'clean', 'aggro', 'gold'].map(t => (
                <button key={t} onClick={() => setSelectedTheme(t)} className={`h-8 rounded border ${selectedTheme === t ? 'border-emerald-500 bg-emerald-500/50' : 'border-zinc-700 bg-zinc-800'}`} title={t}></button>
              ))}
            </div>
          </div>

          <div className="space-y-2">
             <label className="text-xs font-bold text-zinc-500 uppercase tracking-wider block">Assets</label>
             <label className="flex items-center gap-2 p-2 bg-black border border-zinc-700 rounded cursor-pointer hover:border-emerald-500">
                <ImageIcon className="w-4 h-4 text-zinc-400" /> <span className="text-xs text-zinc-300">Background Image</span>
                <input type="file" className="hidden" onChange={(e) => e.target.files[0] && setCustomBg(URL.createObjectURL(e.target.files[0]))} />
             </label>
             <label className="flex items-center gap-2 p-2 bg-black border border-zinc-700 rounded cursor-pointer hover:border-emerald-500">
                <Camera className="w-4 h-4 text-zinc-400" /> <span className="text-xs text-zinc-300">Org Logo</span>
                <input type="file" className="hidden" onChange={(e) => e.target.files[0] && setCustomLogo(URL.createObjectURL(e.target.files[0]))} />
             </label>
          </div>

          {/* ADVANCED OVERLAY CONTROLS */}
          <div className="space-y-2 bg-black/20 p-3 rounded border border-zinc-800">
             <label className="text-xs font-bold text-zinc-500 uppercase flex items-center gap-2"><Move className="w-3 h-3"/> Layout Adjustments</label>
             
             <div className="grid grid-cols-2 gap-2 pt-2">
                 <div>
                    <span className="text-[10px] text-zinc-400 block">Position Y ({tableYOffset}px)</span>
                    <input type="range" min="0" max="600" value={tableYOffset} onChange={e => setTableYOffset(e.target.value)} className="w-full h-1 bg-zinc-700 rounded cursor-pointer" />
                 </div>
                 <div>
                    <span className="text-[10px] text-zinc-400 block">Position X ({tableXOffset}px)</span>
                    <input type="range" min="-100" max="100" value={tableXOffset} onChange={e => setTableXOffset(e.target.value)} className="w-full h-1 bg-zinc-700 rounded cursor-pointer" />
                 </div>
                 <div>
                    <span className="text-[10px] text-zinc-400 block">Row Spacing ({rowSpacing}px)</span>
                    <input type="range" min="0" max="50" value={rowSpacing} onChange={e => setRowSpacing(e.target.value)} className="w-full h-1 bg-zinc-700 rounded cursor-pointer" />
                 </div>
                 <div>
                    <span className="text-[10px] text-zinc-400 block">Font Size ({fontSize}px)</span>
                    <input type="range" min="8" max="32" value={fontSize} onChange={e => setFontSize(e.target.value)} className="w-full h-1 bg-zinc-700 rounded cursor-pointer" />
                 </div>
                 <div className="col-span-2">
                    <span className="text-[10px] text-zinc-400 block flex items-center gap-2"><Maximize className="w-3 h-3"/> Card Scale (Zoom) {cardScale}%</span>
                    <input type="range" min="50" max="150" value={cardScale} onChange={e => setCardScale(e.target.value)} className="w-full h-1 bg-zinc-700 rounded cursor-pointer" />
                 </div>
                 <div className="col-span-2">
                    <span className="text-[10px] text-zinc-400 block">Table Width {tableWidth}%</span>
                    <input type="range" min="50" max="100" value={tableWidth} onChange={e => setTableWidth(e.target.value)} className="w-full h-1 bg-zinc-700 rounded cursor-pointer" />
                 </div>
             </div>
             
             <div className="flex items-center justify-between pt-2">
                <span className="text-xs text-zinc-400">Accent</span>
                <input type="color" value={accentColor} onChange={e => setAccentColor(e.target.value)} className="bg-transparent w-6 h-6 cursor-pointer" />
             </div>
             <div className="flex items-center justify-between">
                <span className="text-xs text-zinc-400">Text Mode</span>
                <div className="flex bg-zinc-800 rounded p-0.5">
                    <button onClick={() => setTextColor('light')} className={`px-2 py-0.5 text-[10px] rounded ${textColor === 'light' ? 'bg-zinc-600 text-white' : 'text-zinc-500'}`}>Light</button>
                    <button onClick={() => setTextColor('dark')} className={`px-2 py-0.5 text-[10px] rounded ${textColor === 'dark' ? 'bg-zinc-600 text-white' : 'text-zinc-500'}`}>Dark</button>
                </div>
             </div>
             {cardMode === 'standings' && (
                <div className="flex items-center justify-between"><span className="text-xs text-zinc-400">2 Columns</span><input type="checkbox" checked={useTwoColumns} onChange={e => setUseTwoColumns(e.target.checked)} className="accent-emerald-500" /></div>
             )}
             <div className="pt-2"><span className="text-xs text-zinc-400 block mb-1">Background Opacity ({tableOpacity}%)</span><input type="range" min="0" max="100" value={tableOpacity} onChange={e => setTableOpacity(e.target.value)} className="w-full h-1 bg-zinc-700 rounded appearance-none cursor-pointer" /></div>
          </div>
          
          <button onClick={downloadCard} className="w-full bg-emerald-500 hover:bg-emerald-400 text-black font-bold py-3 rounded flex items-center justify-center gap-2"><Download className="w-4 h-4" /> Download HD Image</button>
        </div>
      </div>

      <div className="flex-1 bg-zinc-950 flex items-center justify-center p-8 overflow-auto">
        <div 
            id="card-capture"
            className="w-[1080px] min-h-[1920px] shadow-2xl relative overflow-hidden flex flex-col"
            style={{
              backgroundColor: selectedTheme === 'clean' || textColor === 'dark' ? '#f0f0f0' : '#09090b',
              color: textColor === 'dark' ? '#000' : '#fff',
            }}
          >
            {/* BACKGROUND WITH FILTERS */}
            <div className="absolute inset-0 w-full h-full" style={{ filter: `brightness(${bgBrightness}%) contrast(${bgContrast}%) saturate(${bgSaturation}%)` }}>
                {customBg ? ( <img src={customBg} className="absolute inset-0 w-full h-full object-cover" alt="" /> ) : (
                <>
                {selectedTheme === 'cyber' && <div className="absolute inset-0 bg-[radial-gradient(ellipse_at_top,_var(--tw-gradient-stops))] from-zinc-800 via-black to-black"></div>}
                {selectedTheme === 'aggro' && <div className="absolute inset-0 bg-red-950 bg-[url('https://www.transparenttextures.com/patterns/carbon-fibre.png')]"></div>}
                {selectedTheme === 'gold' && <div className="absolute inset-0 bg-gradient-to-br from-yellow-950 via-black to-black"></div>}
                </>
                )}
            </div>
            <div className="absolute inset-0 pointer-events-none opacity-20" style={{ background: `radial-gradient(circle at 50% 0%, ${accentColor}, transparent 70%)` }}></div>

            {/* SCALABLE CONTENT CONTAINER */}
            <div className="absolute inset-0 w-full h-full flex flex-col" style={{ transform: `scale(${cardScale / 100})`, transformOrigin: 'top center' }}>
                
                {/* HEADER */}
                <div className="relative z-10 p-12 flex justify-between items-start" style={{ paddingTop: '80px' }}>
                <div className="flex flex-col gap-1 w-full">
                    <div className="flex items-center gap-4">
                        {customLogo && <img src={customLogo} className="w-28 h-28 object-contain drop-shadow-lg" alt="Org" />}
                        <div className="w-full">
                            <div className="text-xl font-bold tracking-[0.4em] uppercase opacity-70 mb-2"><CardText value={organizerName} onChange={setOrganizerName} /></div>
                            <h1 className="text-8xl font-black uppercase italic tracking-tighter leading-none drop-shadow-lg"><CardText value={cardTitle} onChange={setCardTitle} /></h1>
                            <div className="text-4xl font-bold uppercase tracking-widest opacity-90 mt-2" style={{ color: accentColor }}><CardText value={cardSubtitle} onChange={setCardSubtitle} /></div>
                        </div>
                    </div>
                </div>
                </div>

                {/* CONTENT BODY - FULLY ADJUSTABLE */}
                <div className="relative z-10 p-8 flex-1 transition-all duration-200" 
                    style={{ 
                        paddingTop: `${parseInt(tableYOffset)}px`,
                        paddingLeft: `${parseInt(tableXOffset) + 50}px`,
                        paddingRight: `${50 - parseInt(tableXOffset)}px`
                    }}>
                
                {cardMode === 'standings' && (
                    <div className="w-full mx-auto" style={{ width: `${tableWidth}%` }}>
                        <div className={useTwoColumns ? "grid grid-cols-2 gap-x-12" : "flex flex-col"} style={{ gap: `${rowSpacing}px` }}>
                            {!useTwoColumns && (
                                <div className="grid grid-cols-12 gap-4 text-lg font-bold opacity-70 uppercase px-6 py-3 rounded" style={{ backgroundColor: textColor === 'dark' ? 'rgba(0,0,0,0.1)' : 'rgba(255,255,255,0.1)' }}>
                                    <div className="col-span-1">#</div><div className="col-span-5">Team Name</div><div className="col-span-2 text-center">WWCD</div><div className="col-span-1 text-center">PP</div><div className="col-span-1 text-center">KP</div><div className="col-span-2 text-center">Total</div>
                                </div>
                            )}
                            {results.slice(0, useTwoColumns ? 32 : 20).map((r, i) => (
                                <div key={i} className={`grid grid-cols-12 gap-4 items-center px-6 py-3 rounded-xl relative overflow-hidden`} 
                                    style={{ 
                                    backgroundColor: i === 0 ? accentColor : (textColor === 'dark' ? `rgba(255,255,255,${tableOpacity/100})` : `rgba(20,20,20,${tableOpacity/100})`), 
                                    color: i === 0 ? '#000' : 'inherit',
                                    fontSize: `${fontSize}px`,
                                    marginBottom: `${useTwoColumns ? rowSpacing : 0}px`
                                    }}> 
                                    <div className="col-span-1 font-mono font-black text-2xl opacity-80">{i + 1 < 10 ? `0${i+1}` : i+1}</div>
                                    <div className="col-span-5 font-bold uppercase tracking-tight truncate flex items-center gap-3">
                                        <CardText value={r.teamName} onChange={(val) => updateResultRow(r.id, 'teamName', val)} /> {i === 0 && <Trophy className="w-5 h-5" />}
                                    </div>
                                    <div className="col-span-2 text-center font-mono font-bold opacity-80 text-xl">{r.placement === 1 ? '1' : '-'}</div>
                                    <div className="col-span-1 text-center font-mono opacity-80">{r.placePts}</div>
                                    <div className="col-span-1 text-center font-mono opacity-80">{r.killPts}</div>
                                    <div className="col-span-2 text-center text-3xl font-black">{r.totalPts}</div>
                                </div>
                            ))}
                        </div>
                    </div>
                )}
                </div>

                {/* FOOTER */}
                <div className="relative z-10 p-8 flex justify-between items-center text-white backdrop-blur-md mt-auto" style={{ backgroundColor: 'rgba(0,0,0,0.5)' }}>
                    <div className="flex items-center gap-6">
                        <div className="text-sm font-bold tracking-widest uppercase opacity-60">Follow Us</div>
                        <div className="flex gap-4 text-xl">
                            <Share2 className="w-6 h-6"/> <Globe className="w-6 h-6"/> <MessageCircle className="w-6 h-6"/>
                        </div>
                    </div>
                    <div className="text-sm font-mono opacity-40 uppercase"><CardText value={footerText} onChange={setFooterText} /></div>
                </div>
            </div>
          </div>
      </div>
    </div>
  );

  return (
    <div className="min-h-screen bg-black text-white font-sans selection:bg-emerald-500 selection:text-black">
      <div className="md:hidden p-4 bg-zinc-900 border-b border-zinc-800 flex justify-between items-center">
        <span className="font-bold text-emerald-400">SCRIMMASTER</span>
        <button onClick={() => setActiveTab('dashboard')}><Settings className="w-5 h-5"/></button>
      </div>
      {renderSidebar()}
      <main className="md:ml-64 h-screen overflow-y-auto">
        {activeTab === 'dashboard' && (
             <div className="p-10 flex flex-col items-center justify-center h-full text-center animate-fade-in">
             <div className="w-20 h-20 bg-emerald-500/10 rounded-full flex items-center justify-center mb-6 text-emerald-400"><Trophy className="w-10 h-10" /></div>
             <h1 className="text-5xl font-black text-white mb-4">ESPORTS MANAGER PRO</h1>
             <p className="text-zinc-400 max-w-lg text-lg mb-8">Professional automated scorecard generator.</p>
             <button onClick={() => setActiveTab('teams')} className="group bg-emerald-500 hover:bg-emerald-400 text-black px-8 py-4 rounded-full font-bold text-xl flex items-center gap-3 transition-all transform hover:scale-105">Start New Tournament <ChevronRight className="group-hover:translate-x-1 transition-transform"/></button>
           </div>
        )}
        {activeTab === 'teams' && (
            <div className="p-8 max-w-5xl mx-auto">
            <div className="flex justify-between items-center mb-6"><h1 className="text-3xl font-bold text-white">Step 1: Add Teams</h1><span className="text-zinc-500 text-sm">Supports Auto-Tagging</span></div>
            <div className="grid grid-cols-1 lg:grid-cols-2 gap-8">
              <div className="space-y-4">
                <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800"><textarea value={importText} onChange={(e) => setImportText(e.target.value)} className="w-full h-48 bg-black border border-zinc-700 text-white p-4 rounded-lg font-mono text-sm focus:border-emerald-500 outline-none" placeholder="Paste List Here..."/><button onClick={handleBulkImport} className="w-full mt-4 bg-zinc-800 hover:bg-zinc-700 text-white py-3 rounded-lg font-bold flex items-center justify-center gap-2 border border-zinc-700"><FileText className="w-4 h-4" /> Add to Roster</button></div>
              </div>
              <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800 flex flex-col h-[400px]">
                <div className="flex justify-between items-center mb-4 pb-4 border-b border-zinc-800"><h3 className="font-bold text-white">Registered Teams ({teams.length})</h3><button onClick={() => setTeams([])} className="text-red-400 text-xs hover:underline flex items-center gap-1"><Trash2 className="w-3 h-3"/> Clear</button></div>
                <div className="overflow-y-auto flex-1 space-y-2 pr-2 custom-scrollbar">
                  {teams.map((t, i) => (
                    <div key={i} className="flex items-center gap-3 bg-black/40 p-2 rounded border border-zinc-800/50"><span className="w-6 h-6 bg-zinc-800 rounded flex items-center justify-center text-xs text-zinc-400">{t.slot}</span><div className="flex-1"><div className="text-sm font-bold text-zinc-200">{t.name}</div></div><div className="px-2 py-1 bg-emerald-500/10 text-emerald-400 text-xs font-mono rounded border border-emerald-500/20">{t.tag}</div></div>
                  ))}
                </div>
              </div>
            </div>
            <div className="fixed bottom-0 left-0 md:left-64 right-0 p-4 bg-zinc-900/90 border-t border-zinc-800 flex justify-end backdrop-blur-md"><button onClick={() => setActiveTab('entry')} disabled={teams.length === 0} className="bg-emerald-500 disabled:opacity-50 disabled:cursor-not-allowed hover:bg-emerald-400 text-black px-6 py-3 rounded-lg font-bold flex items-center gap-2">Next: Enter Results <ChevronRight className="w-5 h-5" /></button></div>
          </div>
        )}
        {activeTab === 'entry' && renderDataEntry()}
        {activeTab === 'studio' && renderStudio()}
        {activeTab === 'points' && (
             <div className="p-8 pb-32">
             <h1 className="text-3xl font-bold mb-4">Settings</h1>
             <div className="grid grid-cols-1 gap-6">
               <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800"><h3 className="font-bold mb-4 flex items-center gap-2"><Crosshair className="w-5 h-5 text-red-400"/> Kill Points</h3><div className="flex items-center gap-4"><label className="text-zinc-400 text-sm">Points per Kill:</label><input type="number" value={pointSystem.killPoint} onChange={(e) => setPointSystem({...pointSystem, killPoint: e.target.value})} className="bg-black border border-zinc-700 p-2 rounded w-24 text-white text-center font-bold text-lg" /></div></div>
               <div className="bg-zinc-900 p-6 rounded-xl border border-zinc-800"><h3 className="font-bold mb-4 flex items-center gap-2"><Trophy className="w-5 h-5 text-yellow-400"/> Placement Points</h3><div className="grid grid-cols-2 md:grid-cols-4 lg:grid-cols-8 gap-3">{Object.entries(pointSystem.placements).map(([rank, pts]) => (<div key={rank} className="bg-black p-2 rounded border border-zinc-800 flex flex-col items-center"><span className="text-[10px] text-zinc-500 uppercase font-bold">Rank #{rank}</span><input type="number" value={pts} onChange={(e) => setPointSystem(prev => ({...prev, placements: { ...prev.placements, [rank]: parseInt(e.target.value) || 0 }}))} className="bg-transparent text-white text-center font-bold w-full outline-none"/></div>))}</div></div>
             </div>
           </div>
        )}
      </main>
    </div>
  );
}